# Generated by Django 3.2.4 on 2021-06-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Inicio', '0002_auto_20210617_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='totalprecio',
        ),
        migrations.AddField(
            model_name='carrito',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999999),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='listaprod',
            field=models.ManyToManyField(default=None, to='App_Inicio.Producto'),
        ),
    ]
