# Generated by Django 3.2.4 on 2021-06-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Inicio', '0003_auto_20210618_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
