# Generated by Django 3.2.4 on 2021-06-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Inicio', '0004_carrito_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad',
        ),
    ]
