# Generated by Django 3.2.4 on 2021-06-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Inicio', '0006_auto_20210622_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productocarrito',
            old_name='producto',
            new_name='item',
        ),
        migrations.AddField(
            model_name='carrito',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
