# Generated by Django 3.2.4 on 2021-06-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Inicio', '0007_auto_20210622_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='listaprod',
            new_name='items',
        ),
    ]
