# Generated by Django 3.2.4 on 2021-06-26 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Inicio', '0008_rename_listaprod_carrito_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='items',
            field=models.ManyToManyField(to='App_Inicio.ProductoCarrito'),
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.DecimalField(decimal_places=2, default=0, max_digits=999999)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
